### ISSUE TITLE
Is it possible to put required NameIDPolicy to the initial AuthNRequest?

### ISSUE THREAD

**Issue by sitya** [OpenConext/Stepup-Gateway#177]
Hey, I am just wondering if it is possible to make the Gateway to issue the AuthNRequest to the IdP with 
```xml
<samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" AllowCreate="true"/>
 ```

option in it? It seems that without explicitly required nameidformat the IdPs always send back the response with TransientNameID, which is useless.

Thanks.

**Comment by sitya** [comment]
I guess I should patch this function: https://github.com/OpenConext/Stepup-saml-bundle/blob/develop/src/SAML2/AuthnRequestFactory.php#L142 :)

**Comment by pmeulen** [comment]
Yes, as you found, this is hardcoded, but it is not hard to change to something else. For a final solution we should make this a configuration parameter.

You can typically configure the NameIDPolicy that the IdP responds with on the IdP so you shouldn;t need to change this in the Stepup-Gateway. Is there any reason that this infeasible now?

**Comment by sitya** [comment]
Thanks.

> Is there any reason that this infeasible now?

If I use Stepup in a full-mesh federation, it would take a lots of effort to make all IdP to force using persistentNameID for an SP even it is not requested explicitly.

However it could be enough if I can configure the metadata generator (https://gateway.tld/authentication/metadata) to contain NameIDFormat under SPSSODescriptor. I am gonna check it.

**Comment by pmeulen** [comment]
Running the Stepup-Gateway IdP in a full mesh federation will require more work than. We run the Stepup-Gateway IdP behind a proxy, so it always connects to the same SP entity (that of its proxy). Logic in the proxy to work with multiple IdPs is not there, e.g. it can't show a WAYF.

**Comment by sitya** [comment]
Yup. In our current case we are trying to use with a Satosa as a proxy, but it also sends persistentNameID if only it is required explicitly, and it would be easy to configure on Stepup's side. :)

**Comment by pmeulen** [comment]
OK. Making this configurable through parameters.yml makes the most sense to me. Feel free to open a PR and to discuss implementation options beforehand.

**Comment by sitya** [comment]
Ok, thanks.
