### ISSUE TITLE
GSSP metadata-endpoint not working

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Stepup-Gateway#244]
When accessing `/gssp/azuremfa/metadata`

`
Mar 28 16:45:50 sv2010532 STEPUP-GATEWAY[11620]: {"channel":"request","level":"CRITICAL","message":"Uncaught PHP Exception TypeError: \"Argument 1 passed to Surfnet\\SamlBundle\\Metadata\\MetadataFactory::__construct() must be an instance of Twig\\Environment, instance of Symfony\\Bundle\\TwigBundle\\TwigEngine given, called in /var/cache/stepup/gateway/ContainerVl8xQ0Q/srcApp_KernelProdContainer.php on line 1295\" at /apps/installation/Stepup-Gateway/Stepup-Gateway-3.4.5/vendor/surfnet/stepup-saml-bundle/src/Metadata/MetadataFactory.php line 57","context":{"exception":{"class":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","message":"Argument 1 passed to Surfnet\\SamlBundle\\Metadata\\MetadataFactory::__construct() must be an instance of Twig\\Environment, instance of Symfony\\Bundle\\TwigBundle\\TwigEngine given, called in /var/cache/stepup/gateway/ContainerVl8xQ0Q/srcApp_KernelProdContainer.php on line 1295","code":0,"file":"/apps/installation/Stepup-Gateway/Stepup-Gateway-3.4.5/vendor/surfnet/stepup-saml-bundle/src/Metadata/MetadataFactory.php:57"}},"extra":{"art":"23200","server":"gateway.stepup.example.org","application":"stepup-gateway","request_id":"7b08b5faf7240f55aa638dea74d8d3ee"}}`

**Comment by phavekes** [comment]
Resolved in #248
